name: Pre-Production Deployment

'on':
  push:
    branches:
      - master

jobs:
  staging_deploy:
    name: Staging Deployment
    runs-on: ubuntu-latest
    environment: Staging
    steps:
      - uses: actions/checkout@v4
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_ENVIRONMENT_CI_TOKEN }}"
          channelId: live
          projectId: tarkovtracker-staging