name: Testing Deployment

"on": [ pull_request_target ]

jobs:
  testing_deploy:
    name: Testing Deployment
    runs-on: ubuntu-latest
    environment: Testing
    steps:
      - uses: actions/checkout@v4
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_ENVIRONMENT_CI_TOKEN }}"
          expires: 30d
          projectId: tarkovtracker-testing